"""add game metadata tables

Revision ID: 70e2c6c6ae01
Revises: b7e8541487dc
Create Date: 2025-12-30 02:03:17.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e2c6c6ae01'
down_revision = 'b7e8541487dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create game_metadata table
    op.create_table('game_metadata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('steamgriddb_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('release_date', sa.String(length=64), nullable=True),
        sa.Column('hero_url', sa.String(length=2048), nullable=True),
        sa.Column('logo_url', sa.String(length=2048), nullable=True),
        sa.Column('icon_url', sa.String(length=2048), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_metadata_name'), 'game_metadata', ['name'], unique=False)
    op.create_index(op.f('ix_game_metadata_steamgriddb_id'), 'game_metadata', ['steamgriddb_id'], unique=False)

    # Create video_game_link table
    op.create_table('video_game_link',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('video_id', sa.String(length=32), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['game_id'], ['game_metadata.id'], ),
        sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_game_link')
    op.drop_index(op.f('ix_game_metadata_steamgriddb_id'), table_name='game_metadata')
    op.drop_index(op.f('ix_game_metadata_name'), table_name='game_metadata')
    op.drop_table('game_metadata')
    # ### end Alembic commands ###
