"""add video recorded_at and source_folder

Revision ID: f1a2b3c4d5e6
Revises: 70e2c6c6ae01
Create Date: 2026-01-03 17:27:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = '70e2c6c6ae01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source_folder', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('source_folder')
        batch_op.drop_column('recorded_at')
    # ### end Alembic commands ###
